//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LabelUp_Admin.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class BusinessEntities : DbContext
    {
        public BusinessEntities()
            : base("name=BusinessEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<sysdiagrams> sysdiagrams { get; set; }
        public virtual DbSet<tbl_Estampa_GrupoEstampa> tbl_Estampa_GrupoEstampa { get; set; }
        public virtual DbSet<tbl_Estampas> tbl_Estampas { get; set; }
        public virtual DbSet<tbl_Grupo_Estampas> tbl_Grupo_Estampas { get; set; }
        public virtual DbSet<tbl_Plantillas> tbl_Plantillas { get; set; }
        public virtual DbSet<tbl_Plantillas_Estampas> tbl_Plantillas_Estampas { get; set; }
        public virtual DbSet<tbl_Productos> tbl_Productos { get; set; }
        public virtual DbSet<tbl_Productos_Plantillas> tbl_Productos_Plantillas { get; set; }
        public virtual DbSet<tbl_Usuarios> tbl_Usuarios { get; set; }
        public virtual DbSet<v_EstampaPlantillaGrupoEstampa> v_EstampaPlantillaGrupoEstampa { get; set; }
        public virtual DbSet<tbl_cart> tbl_cart { get; set; }
        public virtual DbSet<tbl_Estados_Pedido> tbl_Estados_Pedido { get; set; }
        public virtual DbSet<tbl_Pedidos> tbl_Pedidos { get; set; }
        public virtual DbSet<tbl_PrametrosPersonalizacion> tbl_PrametrosPersonalizacion { get; set; }
        public virtual DbSet<tbl_Envios_Parametros> tbl_Envios_Parametros { get; set; }
        public virtual DbSet<AspNetUsers> AspNetUsers { get; set; }
        public virtual DbSet<v_grupoEstampaPlantilla> v_grupoEstampaPlantilla { get; set; }
        public virtual DbSet<tbl_grupoImagen> tbl_grupoImagen { get; set; }
        public virtual DbSet<tbl_Imagenes> tbl_Imagenes { get; set; }
    }
}
