//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LabelUp_Admin.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbl_Productos_Plantillas
    {
        public int Id { get; set; }
        public int Id_Producto { get; set; }
        public int Id_Plantilla { get; set; }
        public bool Activo { get; set; }
        public bool Eliminado { get; set; }
        public Nullable<decimal> Precio { get; set; }
    
        public virtual tbl_Plantillas tbl_Plantillas { get; set; }
        public virtual tbl_Productos tbl_Productos { get; set; }
    }
}
