//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LabelUp_Admin.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbl_PrametrosPersonalizacion
    {
        public int Id { get; set; }
        public Nullable<int> Id_Plantilla { get; set; }
        public Nullable<int> X { get; set; }
        public Nullable<int> Y { get; set; }
        public Nullable<int> W { get; set; }
        public Nullable<int> H { get; set; }
        public Nullable<int> CuadroTexto { get; set; }
        public Nullable<int> Zoom { get; set; }
    
        public virtual tbl_Plantillas tbl_Plantillas { get; set; }
    }
}
