//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LabelUp_Admin.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbl_Plantillas_Estampas
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public tbl_Plantillas_Estampas()
        {
            this.tbl_cart = new HashSet<tbl_cart>();
        }
    
        public int Id { get; set; }
        public int Id_Plantilla { get; set; }
        public int Id_Estampa { get; set; }
        public int Id_ImagenPlantilla { get; set; }
        public bool Activo { get; set; }
        public bool Eliminado { get; set; }
    
        public virtual tbl_Estampas tbl_Estampas { get; set; }
        public virtual tbl_Plantillas tbl_Plantillas { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tbl_cart> tbl_cart { get; set; }
        public virtual tbl_Imagenes tbl_Imagenes { get; set; }
    }
}
