//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LabelUp_Admin.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbl_cart
    {
        public int Id { get; set; }
        public Nullable<System.DateTime> Fecha { get; set; }
        public Nullable<int> Id_Estado { get; set; }
        public Nullable<int> Id_Usuario { get; set; }
        public Nullable<System.Guid> keyUser { get; set; }
        public Nullable<int> Id_Producto { get; set; }
        public Nullable<int> Id_Plantilla { get; set; }
        public Nullable<int> Id_Estampa { get; set; }
        public string Param1 { get; set; }
        public string Param2 { get; set; }
        public string Param3 { get; set; }
        public string Param4 { get; set; }
        public Nullable<int> ParamSize1 { get; set; }
        public Nullable<int> ParamSize2 { get; set; }
        public Nullable<int> ParamSize3 { get; set; }
        public Nullable<int> ParamSize4 { get; set; }
        public string FontName { get; set; }
        public string FontColor { get; set; }
        public Nullable<decimal> PrecioUnitario { get; set; }
        public Nullable<decimal> Cantidad { get; set; }
        public Nullable<decimal> Total { get; set; }
        public Nullable<int> Id_PlantillaEstampa { get; set; }
        public Nullable<int> Id_Pedido { get; set; }
    
        public virtual tbl_Estampas tbl_Estampas { get; set; }
        public virtual tbl_Estados_Pedido tbl_Estados_Pedido { get; set; }
        public virtual tbl_Plantillas tbl_Plantillas { get; set; }
        public virtual tbl_Productos tbl_Productos { get; set; }
        public virtual tbl_Usuarios tbl_Usuarios { get; set; }
        public virtual tbl_Plantillas_Estampas tbl_Plantillas_Estampas { get; set; }
        public virtual tbl_Pedidos tbl_Pedidos { get; set; }
    }
}
