//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LabelUp_Admin.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbl_Plantillas
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public tbl_Plantillas()
        {
            this.tbl_Plantillas_Estampas = new HashSet<tbl_Plantillas_Estampas>();
            this.tbl_Productos_Plantillas = new HashSet<tbl_Productos_Plantillas>();
            this.tbl_cart = new HashSet<tbl_cart>();
            this.tbl_PrametrosPersonalizacion = new HashSet<tbl_PrametrosPersonalizacion>();
        }
    
        public int Id { get; set; }
        public string Codigo { get; set; }
        public string Nombre { get; set; }
        public string Descripcion { get; set; }
        public Nullable<int> Id_imagen { get; set; }
        public Nullable<int> Id_imagenPlantilla { get; set; }
        public Nullable<bool> Visible { get; set; }
        public Nullable<bool> Eliminado { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tbl_Plantillas_Estampas> tbl_Plantillas_Estampas { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tbl_Productos_Plantillas> tbl_Productos_Plantillas { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tbl_cart> tbl_cart { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tbl_PrametrosPersonalizacion> tbl_PrametrosPersonalizacion { get; set; }
        public virtual tbl_Imagenes tbl_Imagenes { get; set; }
        public virtual tbl_Imagenes tbl_Imagenes1 { get; set; }
    }
}
