//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LabelUp_Admin.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbl_Pedidos
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public tbl_Pedidos()
        {
            this.tbl_cart = new HashSet<tbl_cart>();
        }
    
        public int Id { get; set; }
        public Nullable<System.DateTime> Fecha { get; set; }
        public Nullable<int> Id_Usuario { get; set; }
        public Nullable<int> Id_Envio { get; set; }
        public Nullable<int> Id_Pago { get; set; }
        public Nullable<int> Id_Estado { get; set; }
        public Nullable<decimal> Total { get; set; }
        public Nullable<System.Guid> keyUser { get; set; }
        public string MedioPago { get; set; }
        public string Direccion_Facturacion { get; set; }
        public string Direccion_Entrega { get; set; }
        public string Facturacion_Nombre_Apellido { get; set; }
        public string Facturacion_Piso { get; set; }
        public string Facturacion_Dto { get; set; }
        public string Facturacion_CP { get; set; }
        public string Entrga_Nombre_Apellido { get; set; }
        public string Entrega_Piso { get; set; }
        public string Entrega_Dto { get; set; }
        public string Entrega_CP { get; set; }
        public string MercadoPagoId { get; set; }
        public string MercadoPagoStatus { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tbl_cart> tbl_cart { get; set; }
        public virtual tbl_Estados_Pedido tbl_Estados_Pedido { get; set; }
        public virtual tbl_Usuarios tbl_Usuarios { get; set; }
        public virtual tbl_Envios_Parametros tbl_Envios_Parametros { get; set; }
    }
}
