//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LabelUp_Admin.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbl_Envios_Parametros
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public tbl_Envios_Parametros()
        {
            this.tbl_Pedidos = new HashSet<tbl_Pedidos>();
        }
    
        public int Id { get; set; }
        public string Codigo_Postal { get; set; }
        public string Localidad { get; set; }
        public Nullable<bool> Eliminado { get; set; }
        public Nullable<decimal> Costo_Envio { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tbl_Pedidos> tbl_Pedidos { get; set; }
    }
}
