//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LabelUp_Admin.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class v_grupoEstampaPlantilla
    {
        public int id { get; set; }
        public string Codigo { get; set; }
        public string Nombre { get; set; }
        public string Descripcion { get; set; }
        public Nullable<int> Id_Imagen { get; set; }
        public bool Visible { get; set; }
        public bool Eliminado { get; set; }
        public int Id_Plantilla { get; set; }
        public string URI { get; set; }
        public int Id_Producto { get; set; }
    }
}
