CREATE TABLE [dbo].[tbl_cart]
(
	[Id] INT IDENTITY(1,1) NOT NULL PRIMARY KEY,
	Fecha datetime,
	Id_Estado INT,
	Id_Usuario INT,
	keyUser uniqueidentifier,
	Id_Producto INT,
	Id_Plantilla INT,
	Id_Estampa INT,
	Param1 varchar(200),
	Param2 varchar(200),
	Param3 varchar(200),
	Param4 varchar(200),
	ParamSize1 INT,
	ParamSize2 INT,
	ParamSize3 INT,
	ParamSize4 INT,
	FontName varchar(100),
	FontColor varchar(50),
	PrecioUnitario decimal(18,2),
	Cantidad decimal(18,2),
	Total decimal(18,2),
	Id_Pedido int,
	 FOREIGN KEY ([Id_Producto]) REFERENCES [dbo].[tbl_Productos] ([Id]),
	 FOREIGN KEY ([Id_Plantilla]) REFERENCES [dbo].[tbl_Plantillas] ([Id]),
	 FOREIGN KEY ([Id_Estampa]) REFERENCES [dbo].[tbl_Estampas] ([Id]),
	 FOREIGN KEY ([Id_Usuario]) REFERENCES [dbo].[tbl_Usuarios] ([Id]),
	 FOREIGN KEY ([Id_Estado]) REFERENCES [dbo].[tbl_Estados_Pedido] ([Id]),
	 FOREIGN KEY ([Id_Pedido]) REFERENCES [dbo].[tbl_Pedidos] (Id)
)